### ISSUE TITLE
updating the mirror from jerasure.org

### ISSUE THREAD

**Issue by dachary** [tsuraan/Jerasure#15]
it would be nice to update the mirror on a regular basis from http://lab.jerasure.org/jerasure/jerasure.git . I would be happy to take care of this if you'd like. When searching for jerasure in google, your repository shows first and it currently gives the impression that the library has not been updated since 2014 :-)

**Comment by tsuraan** [comment]
Yeah, I can definitely do that. Are there any branches you want me to track, or just the master?

**Comment by dachary** [comment]
master and v2 will be great. They are the only branches at http://jerasure.org/jerasure/jerasure/branches and the idea is that this upstream repository will never be poluted with branches that are in progress or even for integration purposes. You should be good with something like:
<pre>
git fetch origin +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
git push mirror +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
</pre>

**Comment by tsuraan** [comment]
Ok, I now have my Pi syncing jerasure.org's master and v2 to my github every 8 hours. Hopefully that will just keep going on its own.

**Comment by ghost** [comment]
Awesome, thanks !
